# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_link', models.TextField()),
                ('article_content', models.TextField(null=True)),
                ('article_title', models.CharField(max_length=255, null=True)),
                ('article_content_summary', models.TextField(null=True)),
                ('article_title_summary', models.CharField(max_length=255, null=True)),
                ('published_date', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
    ]
